var url = 'http://123.207.168.112:10000';
$.fn.api.settings.api = {
  'staff login' : url+'/staff/login',
  'staff info' : url+'/staff/info',
  'staff logout' : url+'/staff/logout',
  'shop getAll' : url+'/shop/getAll',
  'shop search' : url+'/shop/search',
  'shop listByPage' : url+'/shop/listByPage',
  'shop insert' : url+'/shop/insert',
  'shop update' : url+'/shop/update',
  'shop delByIds' : url+'/shop/delByIds',
  'stock search' : url+'/stock/search',
  'stock insert' : url+'/stock/insert',
  'stock update' : url+'/stock/update',
  'stock delete' : url+'/stock/delete',
  'stockType getAll' : url+'/stockType/getAll',
  'stockType search' : url+'/stockType/search',
  'stockType insert' : url+'/stockType/insert',
  'stockType update' : url+'/stockType/update',
  'stockType delete' : url+'/stockType/delete',
};